# Generated by Django 5.0.1 on 2024-02-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['name', 'age']},
        ),
    ]
