# Generated by Django 5.0.1 on 2024-02-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_hospitalvaccine_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalvaccine',
            options={'ordering': ['status']},
        ),
    ]
