# Generated by Django 5.0.1 on 2024-02-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_hospitalvaccine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalvaccine',
            options={'ordering': ['status', 'vaccine']},
        ),
    ]
