# Generated by Django 5.0.1 on 2024-02-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_hospitalvaccine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['age', 'name']},
        ),
    ]
