# Generated by Django 5.0.1 on 2024-02-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_child_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvaccine',
            name='status',
            field=models.CharField(choices=[('TOSHIP', 'ToShip'), ('TORECEIVE', 'ToReceive'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='TOSHIP', max_length=50),
        ),
    ]
